layout_spectrum: 0
color:
  saturation: 0.9626329
  lightness: 0.9408602
  brandStrength: 0.5017921
  rhythmicContrast: 0.5681003
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
typography_spectrum: 0.5441777
name: JMSMedia
